### ISSUE TITLE
Docker stopping issue

### ISSUE THREAD

**Issue by gbiagomba** [stefanoj3/dirstalk#92]
Hello @stefanoj3 , we meet again lol!

Humor aside, when I ran dirstalk in docker i noticed if i tried do to either ctrl+z or ctrl+c it didnt stop the program but instead moved to the next procedural phase. I had to hit it a few times to eventually make it stop. I am not sure if you were aware but I figured I let you know. Its a minor issue but ya.

**Comment by stefanoj3** [comment]
Hey, thank you for reporting the issue @gbiagomba, your reports are very appreciated!

I will try to reproduce it and if manage I will try to come up with a way to make the shutdown work better in docker.

**Comment by stefanoj3** [comment]
@gbiagomba I tried to reproduce and it works fine for me.

First signint is gonna signal the threads to shut down, the application will try to stop gracefully, the second one will make it just stop.

Are you running docker on a mac? I have tried on linux.

**Comment by gbiagomba** [comment]
@stefanoj3 I was running it in kali but that makes sense, i guess i was expecting it to stop right away. But duly noted & sorry for the late reply

**Comment by stefanoj3** [comment]
@gbiagomba No worries, any report is welcome!

**Comment by gbiagomba** [comment]
@stefanoj3 if you are ever in philly, i will get you a TRUE philly cheesesteak and a beer to go with it :)

**Comment by stefanoj3** [comment]
@gbiagomba I will keep it in mind :)

**Comment by gbiagomba** [comment]
@stefanoj3 I was going to come to berlin this year but that got scrapped but i will be in the neighborhood next year (god willing)

**Comment by stefanoj3** [comment]
@gbiagomba Then next year a beer (or multiple ones) is in order :)

**Comment by gbiagomba** [comment]
i have you in my calendar sir, i will be reaching out when i come! @stefanoj3

**Comment by stefanoj3** [comment]
Feel free to drop me an email @gbiagomba `esse.gab2 at gmail dot com`

**Comment by gbiagomba** [comment]
I sent you a calendar invite @stefanoj3 for a tentative date :)
